# Generated by Django 4.2 on 2025-11-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_foto_alter_puntaje_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='estado',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='inscripcion',
            table='core_inscripcion',
        ),
    ]
