# Generated by Django 4.2 on 2025-11-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_inscripcion_estado_alter_inscripcion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('activo', 'Activo'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20),
        ),
    ]
