# Generated by Django 4.2 on 2025-11-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
