# Generated by Django 4.2.29 on 2026-04-22 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_denuncia_comentario_reaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionDestacada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('puntos_sugeridos', models.IntegerField(default=5)),
                ('validada', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_accion_destacada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('presente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='reaccion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reaccion',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='reaccion',
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='puntaje',
            name='jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jornada'),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='justificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
        migrations.DeleteModel(
            name='Reaccion',
        ),
    ]
