# Generated by Django 4.2.29 on 2026-04-29 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_acciondestacada_asistencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.temaforo')),
            ],
            options={
                'db_table': 'core_comentario_foro',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReaccionForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('me_gusta', 'Me gusta'), ('no_me_gusta', 'No me gusta'), ('me_encanta', 'Me encanta')], max_length=20)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='core.temaforo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'core_reaccion_foro',
                'unique_together': {('tema', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='DenunciaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='core.temaforo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'db_table': 'core_denuncia_foro',
                'unique_together': {('tema', 'usuario')},
            },
        ),
    ]
