# Generated by Django 4.2.29 on 2026-05-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comentarioforo_reaccionforo_denunciaforo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id_recordatorio', models.AutoField(primary_key=True, serialize=False)),
                ('periodicidad', models.CharField(choices=[('24h', '24 horas antes'), ('1h', '1 hora antes'), ('30min', '30 minutos antes')], default='24h', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('jornada', models.ForeignKey(db_column='jornada_id', on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='core.jornada')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='core.usuario')),
            ],
            options={
                'db_table': 'core_recordatorio',
            },
        ),
    ]
